tracks = [
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/01+-+d.s.+car+jam.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/02+-+theatre+is+the+life+of+you.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/03+-+viet+nam.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/04+-+cohesion.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/05+-+it\'s+expected+i\'m+gone.mp3',
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/06+-+\#1+hit+song.mp3",
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/07+-+two+beads+at+the+end.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/08+-+do+you+want+new+wave+or+do+you+want+the+truth.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/09+-+don\'t+look+now.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/10+-+shit+from+an+old+notebook.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/11+-+nature+without+man.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/12+-+one+reporter\'s+opinion.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/13+-+political+song+for+michael+jackson+to+sing.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/14+-+maybe+partying+will+help.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/15+-+toadies.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/16+-+retreat.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/17+-+the+big+foist.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/18+-+god+bows+to+math.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/19+-+corona.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/20+-+the+glory+of+man.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/21+-+take+5+d.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/22+-+my+heart+and+the+real+world.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/23+-+history+lesson+-part2.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/24+-+you+need+the+glory.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/25+-+the+roar+of+the+masses+could+be+farts.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/26+-+west+germany.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/27+-+the+politics+of+time.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/28+-+themselves.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/29+-+please+don\'t+be+gentle+with+me.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/30+-+nothing+indeed.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/31+-+no+exchange.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/32+-+there+ain\'t+shit+on+tv+tonight.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/33+-+this+ain\'t+no+picnic.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/34+-+spillage.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/35+-+untitledsong+for+latin+america.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/36+-+jesus+and+tequila.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/37+-+june+16th.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/38+-+storm+in+my+house.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/39+-+martin\'s+story.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/40+-+dr.+wu.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/41+-+the+world+according+to+nouns.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/42+-+love+dance.mp3',
'https://s3.amazonaws.com/sstify-dev/seeds/tracks/1984+-+Double+Nickels+On+The+Dime/43+-+three+car+jam.mp3',
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1983+-+Meat+Puppets+II/01+-+split+myself+in+two.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1983+-+Meat+Puppets+II/02+-+magic+toy+missing.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1983+-+Meat+Puppets+II/03+-+lost.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1983+-+Meat+Puppets+II/04+-+plateau.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1983+-+Meat+Puppets+II/05+-+aurora+borealis.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1983+-+Meat+Puppets+II/06+-+we\'re+here.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1983+-+Meat+Puppets+II/07+-+climbing.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1983+-+Meat+Puppets+II/08+-+new+gods.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1983+-+Meat+Puppets+II/09+-+oh\,+me.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1983+-+Meat+Puppets+II/10+-+lake+of+fire.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1983+-+Meat+Puppets+II/11+-+i\'m+a+mindless+idiot.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1983+-+Meat+Puppets+II/12+-+the+whistling+song.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1986+-+Evol/01+-+tom+violence.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1986+-+Evol/02+-+shadow+of+a+doubt.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1986+-+Evol/03+-+star+power.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1986+-+Evol/04+-+in+the+kingdom+\#19.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1986+-+Evol/05+-+green+light.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1986+-+Evol/06+-+death+to+our+friends.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1986+-+Evol/07+-+secret+girl.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1986+-+Evol/08+-+marilyn+moore.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/1986+-+Evol/09+-+expressway+to+your+skull.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Black+Flag+-+My+War/black+flag+-+my+war+-+01+-+my+war.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Black+Flag+-+My+War/black+flag+-+my+war+-+02+-+can\'t+decide.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Black+Flag+-+My+War/black+flag+-+my+war+-+03+-+beat+my+head+against+the+wall.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Black+Flag+-+My+War/black+flag+-+my+war+-+04+-+i+love+you.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Black+Flag+-+My+War/black+flag+-+my+war+-+05+-+forever+time.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Black+Flag+-+My+War/black+flag+-+my+war+-+06+-+the+swinging+man.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Black+Flag+-+My+War/black+flag+-+my+war+-+07+-+nothing+left+inside.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Black+Flag+-+My+War/black+flag+-+my+war+-+08+-+three+nights.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Black+Flag+-+My+War/black+flag+-+my+war+-+09+-+scream.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/01+rise+above.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/02+spray+paint.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/03+six+pack.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/04+what+i+see.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/05+tv+party.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/06+thirsty+and+miserable.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/07+police+story.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/08+gimmie+gimmie+gimmie.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/09+depression.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/10+room+13.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/11+damaged+ii.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/12+no+more.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/13+padded+cell.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/14+life+of+pain.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Damaged/15+damaged+i.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Mournful+Cries/01+the+creeps.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Mournful+Cries/02+dragon+time.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Mournful+Cries/03+shooting+gallery.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Mournful+Cries/04+bitter+truth.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Mournful+Cries/05+the+troll.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Mournful+Cries/06+looking+glass.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Sister/01+-+schizophrenia.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Sister/02+-+(i+got+a)+catholic+block.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Sister/03+-+beauty+lies+in+the+eye.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Sister/04+-+stereo+sanctity.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Sister/05+-+pipeline+kill+time.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Sister/06+-+tuff+gnarl.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Sister/07+-+pacific+coast+highway.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Sister/08+-+hot+wire+my+heart.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Sister/09+-+kotton+krown.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Sister/10+-+white+kross.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/We+Became+Snakes/01+we+became+snakes.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/We+Became+Snakes/02+drugstore+logic.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/We+Became+Snakes/03+frankie+on+a+pony.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/We+Became+Snakes/04+the+need.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/We+Became+Snakes/05+for+her+while.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/We+Became+Snakes/06+effort+to+waste.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/We+Became+Snakes/07+the+redeemer.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/We+Became+Snakes/08+longing+for+ether.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/You\'re+Living+All+Over+Me/dinosaur+jr.+-+you\'re+living+all+over+me+-+01+-+little+fury+things.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/You\'re+Living+All+Over+Me/dinosaur+jr.+-+you\'re+living+all+over+me+-+02+-+kracked.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/You\'re+Living+All+Over+Me/dinosaur+jr.+-+you\'re+living+all+over+me+-+03+-+sludgefeast.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/You\'re+Living+All+Over+Me/dinosaur+jr.+-+you\'re+living+all+over+me+-+04+-+the+lung.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/You\'re+Living+All+Over+Me/dinosaur+jr.+-+you\'re+living+all+over+me+-+05+-+raisans.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/You\'re+Living+All+Over+Me/dinosaur+jr.+-+you\'re+living+all+over+me+-+06+-+tarpit.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/You\'re+Living+All+Over+Me/dinosaur+jr.+-+you\'re+living+all+over+me+-+07+-+in+a+jar.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/You\'re+Living+All+Over+Me/dinosaur+jr.+-+you\'re+living+all+over+me+-+08+-+lose.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/You\'re+Living+All+Over+Me/dinosaur+jr.+-+you\'re+living+all+over+me+-+09+-+poledo.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/01+something+i+learned+today.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/02+broken+home,+broken+heart.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/03+never+talking+to+you+again.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/04+chartered+trips.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/05+dreams+reoccurring.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/06+indecision+time.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/07+hare+krsna.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/08+beyond+the+threshold.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/09+pride.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/10+i\'ll+never+forget+you.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/11+the+biggest+lie.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/12+what\'s+going+on.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/13+masochism+world.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/14+standing+by+the+sea.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/15+somewhere.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/16+one+step+at+a+time.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/17+pink+turns+to+blue.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/18+newest+industry.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/19+monday+will+never+be+the+same.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/20+whatever.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/21+the+tooth+fairy+and+the+princess.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/22+turn+on+the+news.mp3",
"https://s3.amazonaws.com/sstify-dev/seeds/tracks/Zen+Arcade/23+reoccurring+dreams.mp3"
]
# User.destroy_all
# User.create(username: 'guest', password: 'password')

Artist.destroy_all
Artist.create(name: 'Black Flag', image: "https://s3.amazonaws.com/sstify-dev/seeds/artists/black_flag.jpg")
Artist.create(name: 'Minutemen', image: "https://s3.amazonaws.com/sstify-dev/seeds/artists/minutemen.jpg")
Artist.create(name: 'Sonic Youth', image: "https://s3.amazonaws.com/sstify-dev/seeds/artists/sonic_youth.jpg")
Artist.create(name: 'Meat Puppets', image: "https://s3.amazonaws.com/sstify-dev/seeds/artists/meat_puppets.jpg")
Artist.create(name: 'Dinosaur Jr.', image: "https://s3.amazonaws.com/sstify-dev/seeds/artists/dinosaur_jr.jpeg")
Artist.create(name: 'Hüsker Dü', image: "https://s3.amazonaws.com/sstify-dev/seeds/artists/husker_du.jpg")
Artist.create(name: 'Saccharine Trust', image: "https://s3.amazonaws.com/sstify-dev/seeds/artists/saccharine_trust.jpg")
Artist.create(name: 'Saint Vitus', image: "https://s3.amazonaws.com/sstify-dev/seeds/artists/saint_vitus.jpg")

Album.destroy_all
Album.create(artist: Artist.find_by_name('Black Flag'), title: 'Damaged', year: 1983, image: 'https://s3.amazonaws.com/sstify-dev/seeds/albums/damaged.jpg')
Album.create(artist: Artist.find_by_name('Black Flag'), title: 'My War', year: 1984, image: 'https://s3.amazonaws.com/sstify-dev/seeds/albums/my_war.jpg')
Album.create(artist: Artist.find_by_name('Sonic Youth'), title: "EVOL", year: 1986, image: 'https://s3.amazonaws.com/sstify-dev/seeds/albums/evol.jpg')
Album.create(artist: Artist.find_by_name('Minutemen'), title: "Double Nickels on the Dime", year: 1984, image: 'https://s3.amazonaws.com/sstify-dev/seeds/albums/double_nickels.jpg')
Album.create(artist: Artist.find_by_name('Meat Puppets'), title: 'Meat Puppets II', year: 1984, image: 'https://s3.amazonaws.com/sstify-dev/seeds/albums/meat_puppets_ii.png')
Album.create(artist: Artist.find_by_name('Saint Vitus'), title: 'Mournful Cries', year: 1988, image: 'https://s3.amazonaws.com/sstify-dev/seeds/albums/mournful_cries.jpg')
Album.create(artist: Artist.find_by_name('Sonic Youth'), title: 'Sister', year: 1987, image: "https://s3.amazonaws.com/sstify-dev/seeds/albums/sister.jpg")
Album.create(artist: Artist.find_by_name('Saccharine Trust'), title: 'We Became Snakes', year: 1986, image: "https://s3.amazonaws.com/sstify-dev/seeds/albums/we_became_snakes.jpg")
Album.create(artist: Artist.find_by_name('Dinosaur Jr.'), title: "You\'re Living All Over Me", year: 1987, image: "https://s3.amazonaws.com/sstify-dev/seeds/albums/youre_living_all_over_me.jpg")
Album.create(artist: Artist.find_by_name('Hüsker Dü'), title: "Zen Arcade", year: 1984, image: "https://s3.amazonaws.com/sstify-dev/seeds/albums/zen_arcade.jpg")


Track.destroy_all
tracks.each do |track|
  Track.create(audio: track)
end
